name: Bounty
description: Bounty Hunter Needed
title: "Bounty Hunter Needed : "
labels: [Bounty Hunter Needed]
assignees:
 Raised-By
body:
  - type: dropdown
    id: Bounty-Level
    attributes:
      label: Bounty-Level
      description: Bounty-Level
      options:
       - Urgent
       - Important
       - Useful
    validations:
      required: true
  - type: dropdown
    id: Complexity
    attributes:
      label: Complexity
      description: Complexity
      options:
       - High Complexity
       - Medium Complexity
       - Low Complexity
    validations:
      required: true
  - type: dropdown
    id: Bounty-Amount
    attributes:
      label: Bounty-Amount
      description: Bounty-Amount
      options:
       - 5 ADA
       - 10 ADA
       - 50 ADA
    validations:
      required: true
  - type: dropdown
    id: Bounty-Bonus
    attributes:
      label: Bounty Bonus
      description: Bounty Bonus
      options:
       - 5 ADA
       - 10 ADA
       - 50 ADA
    validations:
      required: true
  - type: dropdown
    id: Increase-increment
    attributes:
      label: Increase increment
      description: Increase increment
      options:
       - 5 ADA
       - 10 ADA
       - 30 ADA
    validations:
      required: true
  - type: textarea
    id: Bounty
    attributes:
      label: Bounty Description
      description: Please describe in detail the Bounty you are raising.
      render: text
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
