name: Bounty
description: Bounty Hunter Needed
title: "Bounty Hunter Needed : "
labels: [Bounty Hunter Needed]
assignees:
 Raised-By
body:
  - type: textarea
    id: Agenda-Item-Detail
    attributes:
      label: Details of your Agenda Item
      description: Please enter the details of your Agenda Item here.
      placeholder: Please enter the details of your Agenda Item here.
      value: "## Agenda Item"
    validations:
      required: true
  - type: dropdown
    id: Bounty-Level
    attributes:
      label: Bounty-Level
      description: Bounty-Level
      options:
       - Urgent
       - Medium
       - Low
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - "@stephen-rowan"
        - "@FelixfromSwarm"
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
